webproj/webapp/urls.py
from django.urls import path
from webapp import views


app_name = 'webapp'

urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('pic1/',views.pictures,name='pic1'),
    path('pic2/',views.pictures,name='pic2'),
    path('pic3/',views.pictures,name='pic3'),
    path('pictures/',views.pictures,name='pictures'),
]

webproj/webproj/urls.py
from django.contrib import admin
from django.urls import path,include

app_name = 'webapp'

urlpatterns = [
    path('',include('webapp.urls')),
    path('admin/', admin.site.urls),
]

webproj/webapp/models.py
from django.db import models

# Create your models here.

webproj/webapp/views.py
from django.shortcuts import render

# Create your views here.

def homepage(request):
    return render(request,'webapp/homepage.html')

def pictures(request):
    return render(request,'webapp/pictures.html')

def pic1(request):
    return render(request,'webapp/pic1.html')
def pic2(request):
    return render(request,'webapp/pic3.html')
def pic3(request):
    return render(request,'webapp/pic3.html')

webproj/templates/webapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static "images/style.css" %}">
  </head>
  <body>




<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #f8bbd0">
    <a class="navbar-brand mx-auto" href="#">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 612 612" focusable="false" role="img" id='pic'>
        <title>Bootstrap</title>
        <path fill="#563d7c" d="M612 510c0 56.1-45.9 102-102 102H102C45.9 612 0 566.1 0 510V102C0 45.9 45.9 0 102 0h408c56.1 0 102 45.9 102 102v408z"/>
        <path fill="#fff" d="M166.3 133h173.5c32 0 57.7 7.3 77 22s29 36.8 29 66.5c0 18-4.4 33.4-13.2 46.2-8.8 12.8-21.4 22.8-37.8 29.8v1c22 4.7 38.7 15.1 50 31.2 11.3 16.2 17 36.4 17 60.8 0 14-2.5 27.1-7.5 39.2-5 12.2-12.8 22.7-23.5 31.5s-24.3 15.8-41 21-36.5 7.8-59.5 7.8h-164V133zm62.5 149.5h102c15 0 27.5-4.2 37.5-12.8s15-20.8 15-36.8c0-18-4.5-30.7-13.5-38s-22-11-39-11h-102v98.6zm0 156.5h110.5c19 0 33.8-4.9 44.2-14.8 10.5-9.8 15.8-23.8 15.8-41.8 0-17.7-5.2-31.2-15.8-40.8s-25.2-14.2-44.2-14.2H228.8V439z"/>
      </svg>
    enji
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'webapp:homepage' %}">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'webapp:pictures' %}">Pictures</a>
        </li>


      </ul>

    </div>
  </nav>

<div class="container">


        {% block body_block %}

        {% endblock %}
</div>
  </body>
</html>

webproj/templates/webapp/carousel.html
{% extends 'webapp/base.html' %}
{% block body_block %}
{%load static%}


<div class="d-flex justify-content-center">
<div id="carouselExampleSlidesOnly" class="carousel slide " data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="{% static "images/mimi.jpg" %}" class="d-block w-100" alt="fuck">
    </div>
    <div class="carousel-item">
      <img src="{% static "images/mimi2.jpg" %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static "images/mimi3.jpg" %}" class="d-block w-100" alt="...">
    </div>
  </div>
</div>
</div>















{% endblock %}

webproj/templates/webapp/homepage.html
{% extends 'webapp/base.html' %}
{% block body_block %}
{%load static%}
<div class="jumbotron" style="background-color: #fce4ec;">
<h1 class="text-center">Mimi's Homepage</h1>
</div>

<div class="d-flex justify-content-center">

<div class="row">

  <div class="d-flex justify-content-center">
  <div id="carouselExampleSlidesOnly" class="carousel slide " data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active" data-interval="500">
          <img src="{% static "images/mimi.jpg" %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item" data-interval="500">
        <img src="{% static "images/mimi2.jpg" %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item" data-interval="500">
        <img src="{% static "images/mimi3.jpg" %}" class="d-block w-100" alt="...">
      </div>
    </div>
  </div>
  </div>

  <div class="card text-white mb-3" style="background-color: #f48fb1; width: 18rem;">
    <img src="{% static "images/mimipink2s.png" %}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title text-center">Mimi :)</h5>
      <p class="card-text text-center">Here are pictures of Mimi. Click below ;)</p>
      <a href="{% url 'webapp:pictures' %}" style="background-color: pink;" class="btn btn-outline-danger text-white d-flex justify-content-center">Pictures</a>
    </div>
  </div>


<div class="d-flex justify-content-center">
<div id="carouselExampleSlidesOnly" class="carousel slide " data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="{% static "images/mimiclose.jpg" %}" class="d-block w-100" alt="fuck">
    </div>
    <div class="carousel-item">
      <img src="{% static "images/mimiflower.jpg" %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static "images/mimimanny.jpg" %}" class="d-block w-100" alt="...">
    </div>
  </div>
</div>
</div>

</div>
</div>
<!--
<div class="row card-deck">
<div class="card text-white bg-primary mb-3" style="width: 18rem;">
  <img src="static/images/mimi.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Mimi :)</h5>
    <p class="card-text">Here is a picture of Mimi</p>
    <a href="{% url 'webapp:pic1' %}" class="btn btn-warning">Pic1</a>
  </div>
</div>




<div class="card text-white bg-warning mb-3" style="width: 18rem;">
  <img src="static/images/mimi2.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Mimi ;)</h5>
    <p class="card-text">Here is another one</p>
    <a href="{% url 'webapp:pic2' %}" class="btn btn-danger">Pic2</a>
  </div>
</div>

<div class="card text-white bg-success mb-3" style="width: 18rem;">
  <img src="static/images/mimi3.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Mimi c:</h5>
    <p class="card-text">One more for goood measure</p>
    <a href="{% url 'webapp:pic3' %}" class="btn btn-primary">Pic3</a>
  </div>
</div>

</div>



<div class="card">
  <div class="card-header">
    Quote
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>One man's trash is another man's Christmans gift for Dad!</p>
      <footer class="blockquote-footer">Gene Belcher <cite title="Source Title">Bob's Burgers, Season 5:Father of the Bob</cite></footer>
    </blockquote>
  </div>
</div>
-->


{% endblock %}

webproj/templates/webapp/pic1.html
{% extends 'webapp/base.html' %}
{% block body_block %}
{%load static%}

<h1>hi this is a pic1 of mimi</h1>
<img src="{% static "images/mimiyawn.jpg" %}" alt="">


{% endblock %}

webproj/templates/webapp/pic2.html
{% extends 'webapp/base.html' %}
{% block body_block %}
{%load static%}

<h1>hi this is a pic1 of mimi</h1>
<img src="{% static "images/mimitoy.jpg" %}" alt="">


{% endblock %}

webproj/templates/webapp/pic3.html
{% extends 'webapp/base.html' %}
{% block body_block %}
{%load static%}

<h1>hi this is a pic1 of mimi</h1>
<img src="{% static "images/mimipink.jpg" %}" alt="">


{% endblock %}

webproj/templates/webapp/pictures.html
{% extends 'webapp/base.html' %}
{% block body_block %}
{%load static%}






<img id='p' src="{% static "images/mimi.jpg" %}" alt="">
<img id='p' src="{% static "images/mimi2.jpg" %}" alt="">
<img id='p' src="{% static "images/mimi3.jpg" %}" alt="">
<img id='p' src="{% static "images/mimiclose.jpg" %}" alt="">
<img id='p' src="{% static "images/mimiflower.jpg" %}" alt="">
<img id='p' src="{% static "images/mimimanny.jpg" %}" alt="">
<img id='p' src="{% static "images/mimipink.jpg" %}" alt="">
<img id='p' src="{% static "images/mimitoy.jpg" %}" alt="">
<img id='p' src="{% static "images/mimiyawn.jpg" %}" alt="">
<img id='p' src="{% static "images/mimidoor.jpg" %}" alt="">



{% endblock %}